"""Initial migration.

Revision ID: 1171c262654c
Revises: 8d3487fefeaf
Create Date: 2025-03-12 17:02:41.499555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1171c262654c'
down_revision = '8d3487fefeaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('publication_date',
               existing_type=mysql.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index('number_of_pages')
        batch_op.drop_index('price_unit')

    with op.batch_alter_table('companys', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companys', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('price_unit', ['price_unit'], unique=True)
        batch_op.create_index('number_of_pages', ['number_of_pages'], unique=True)
        batch_op.alter_column('publication_date',
               existing_type=sa.DateTime(),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
