"""Initial migration.

Revision ID: 2da6798867cd
Revises: 1171c262654c
Create Date: 2025-03-13 11:45:41.636996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2da6798867cd'
down_revision = '1171c262654c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('writer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writer', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
