"""sync fix

Revision ID: 5408f87cd540
Revises: 1e14b9ec91e9
Create Date: 2025-04-21 06:56:51.301457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5408f87cd540'
down_revision = '1e14b9ec91e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companys', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
