"""Initial migration.

Revision ID: 62efb06ede85
Revises: b196c0c1a705
Create Date: 2025-04-23 16:33:55.524348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62efb06ede85'
down_revision = 'b196c0c1a705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companys', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companys', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
