"""Initial migration.

Revision ID: 8d3487fefeaf
Revises: 637d48a42788
Create Date: 2025-03-12 16:51:00.997199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d3487fefeaf'
down_revision = '637d48a42788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint('authors_ibfk_1', type_='foreignkey')
        batch_op.drop_column('authors_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('authors_ibfk_1', 'authors', ['authors_id'], ['id'])

    # ### end Alembic commands ###
